CREATE TABLE "LONG_DEV"."XXG_SQL" (
"ID" NUMBER NOT NULL ,
"NAME" VARCHAR2(255 BYTE) NULL ,
"ROLE" VARCHAR2(255 BYTE) NULL ,
"DB_URL" VARCHAR2(255 BYTE) NULL ,
"DB_USERNAME" VARCHAR2(255 BYTE) NULL ,
"DB_PASSWORD" VARCHAR2(255 BYTE) NULL ,
"SQL" VARCHAR2(255 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "LONG_DEV"."XXG_SQL"."NAME" IS '名称';
COMMENT ON COLUMN "LONG_DEV"."XXG_SQL"."ROLE" IS '需要权限';
COMMENT ON COLUMN "LONG_DEV"."XXG_SQL"."DB_URL" IS '数据库URL';
COMMENT ON COLUMN "LONG_DEV"."XXG_SQL"."DB_USERNAME" IS '数据库用户名';
COMMENT ON COLUMN "LONG_DEV"."XXG_SQL"."DB_PASSWORD" IS '数据库密码';
COMMENT ON COLUMN "LONG_DEV"."XXG_SQL"."SQL" IS '查询语句';

INSERT INTO "LONG_DEV"."XXG_SQL" VALUES ('1', 'Oracle测试数据明细', 'ROLE_GAME1', 'jdbc:oracle:thin:@172.18.167.194:1521:ext', 'long_dev', 'root', 'select * from TBL_XSQSTDFW_STEP where create_time>=? and create_time<?');
INSERT INTO "LONG_DEV"."XXG_SQL" VALUES ('2', 'MySQL测试数据明细', 'ROLE_GAME2', 'jdbc:mysql://10.230.10.8:3306/auto_deploy?useUnicode=true&characterEncoding=UTF-8', 'hongdian_dev', '123456', 'select id,uuid,type,username as 用户名,time as 时间 from operation_log where time>=? and time<?');


CREATE TABLE "LONG_DEV"."XXG_USER" (
"USERNAME" VARCHAR2(255 BYTE) NOT NULL ,
"PASSWORD" VARCHAR2(255 BYTE) NULL ,
"ROLES" VARCHAR2(255 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "LONG_DEV"."XXG_USER"."USERNAME" IS '用户名';
COMMENT ON COLUMN "LONG_DEV"."XXG_USER"."PASSWORD" IS '登录密码';
COMMENT ON COLUMN "LONG_DEV"."XXG_USER"."ROLES" IS '角色权限';

INSERT INTO "LONG_DEV"."XXG_USER" VALUES ('wucao', '123456', 'ROLE_GAME1,ROLE_GAME2');


ALTER TABLE "LONG_DEV"."XXG_SQL" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "LONG_DEV"."XXG_SQL" ADD PRIMARY KEY ("ID");

ALTER TABLE "LONG_DEV"."XXG_USER" ADD CHECK ("USERNAME" IS NOT NULL);
ALTER TABLE "LONG_DEV"."XXG_USER" ADD PRIMARY KEY ("USERNAME");
